export {
  DEFAULT_OPENROUTER_APP_TITLE,
  DEFAULT_OPENROUTER_EMBED_DIMENSIONS,
  DEFAULT_OPENROUTER_EMBED_MODEL,
  DEFAULT_OPENROUTER_HTTP_REFERER,
  DEFAULT_OPENROUTER_MODEL,
  OPENROUTER_API_BASE_URL,
  chunkArray,
  clampInt,
  clipText,
} from '../shared/config.js';

export const DEFAULT_TOP_K = 100;
export const DEFAULT_PREFETCH_COUNT = 1200;
export const DEFAULT_EMBED_BATCH_SIZE = 80;
