export {
  DEFAULT_OPENROUTER_APP_TITLE,
  DEFAULT_OPENROUTER_EMBED_DIMENSIONS as DEFAULT_EMBEDDING_DIMENSIONS,
  DEFAULT_OPENROUTER_EMBED_MODEL,
  DEFAULT_OPENROUTER_HTTP_REFERER,
  OPENROUTER_API_BASE_URL,
  chunkArray,
  clampInt,
  sleep,
} from '../shared/config.js';

export const DEFAULT_CONCURRENCY = 40;
export const MAX_CONCURRENCY = 200;
export const DEFAULT_RECONCILE_LIMIT = 1000;
export const MAX_RECONCILE_LIMIT = 10000;
export const DEFAULT_STALE_LOCK_SECONDS = 900;
export const DEFAULT_MAX_DURATION_MS = 45_000;
export const MAX_DURATION_MS = 900_000;
export const EMBEDDING_RETRIES = 6;
export const APPLY_CHUNK_SIZE = 20;
export const MARK_CHUNK_SIZE = 500;
